export default {
    time: 'Sets which generator file this entity lives in',
    AIProperties: 'Properties that are encoded in the "AI" bytes in the generator list',
    bEnableOptionalPoint: 'Used for linking entities together physically - like to hang treasures from ceiling string. Add a point to the offset array with a -Z value if doing so.',
    Z: 'The VERTICAL coordinate',
    invasionStartTimeRatio: 'Entity will start walking to base at night at the percentage through the night indicated by this decimal 0-1.0',
    activityTime: 'When in the game should this entity spawn',
    generateNum: 'How many of this entity to spawn. Each one will drop the same thing',
    generateRadius: 'Radius within with to generate multiple entities from generateNum',
    rebirthType: 'Method of respawn',
    birthCond: 'Condition to spawn this enemy',
    wakeCond: 'Condition to spawn this enemy mid-day. Usually used for tide-changes in Serene Shores',
    sleepCond: 'Condition to delete this enemy mid-day. Usually used for tide-changes in Serene Shores',
    bNoChkCondWhenDead: 'Ignores the sleep/wakeCond if entity is dead',
    workNum: 'Pikmin required to complete this task',
    bRegistGenerator: "Set this to true to have the game remember if you collected the treasure",
    valveID: 'ID of the valve - used to link the valve to a sprinkler',
    bSprinklerOnly: 'Permanently enables a sprinkler - set valveID to None if using this',
    piecePutNum: 'Raw material required to build',
    navMeshTriggerID: 'ID of the NavMeshTrigger - used to link them to sprinklers/switches/conveyors etc',
    openTime: 'How long the sprinkler will spray for if single-use',
    bUseSunMeter: 'Makes the waterbox recede at tide change',
    searchTagName: 'Spline name - creatures can be matched to the spline name to try walk along it',
    bAlreadyAppear: 'If false, makes Beady drop from the ceiling',
    navLinkRight: 'Additive vector to apply to entities that jump from this',
    waitTime: 'How long a platform waits upon reaching the end of its spline',
    warpID: 'Links two warp entrances/exits together',
    npcInfoKey: 'The specific NPC that this survivor should be. Refer to the NpcInfo file',
    ignoreList: "Entities that should not be included by this GroupDropManager's group",
    dropPearlScale: "The size of the thing the Pearly Clamclamp is holding"
}